### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/harmonia#1]
These are the milestones for eris - our discord ACME
Project Lead: @jacksebastian17 

[Proposal Doc](https://docs.google.com/document/d/1pgURtOW11w6OxIsPok9e_2PRNATLW244hZ9YR91vBb4/edit)

**Comment by geooot** [comment]
- [ ] make responsive for mobile
- [ ] Make nope button do thing
- [ ] Title should be "Join the TD Discord" instead of harmonia
- [ ] Try to speed it up
